config_sort:
    Runtime:
        disable: false
        parent:
        folder: Runtime
        fullPath: Runtime
        rule: ['*.exe', '*.msi', '*.apk', '*.app', '*.gadget', '*.inf', '*.run', '*.vbs', '*.ws', '*.jar']
        pathStatic: false
    ear:
        disable: false
        parent: Runtime
        folder: ear
        fullPath: Runtime/ear
        rule: ['']
        pathStatic: false
    testsertysyrt:
        disable: false
        parent: ear
        folder: testdthb
        fullPath: Runtime/ear/testdthb
        rule: ['']
        pathStatic: false
    Document:
        disable: false
        parent:
        folder: Document
        fullPath: Document
        rule: ['*.xlsx', '*.docx', '*.pptx', '*.pdf']
        pathStatic: false
    Archive:
        disable: false
        parent:
        folder: Archive
        fullPath: Archive
        rule: ['*.7z', '*.rar', '*.zip', '*.tar', '*.iso', '*.sbx', '*.gz']
        pathStatic: false
    tesqt:
        disable: false
        parent: Archive
        folder: test
        fullPath: Archive/test
        rule: ['']
        pathStatic: false
    testoui:
        disable: false
        parent: tesqt
        folder: test
        fullPath: Archive/test/test
        rule: ['']
        pathStatic: false
    Music:
        disable: false
        parent:
        folder: Music
        fullPath: Music
        rule: ['*.mp3', '*.ogg', '*.flac', '*.wav', '*.aac']
        pathStatic: false
    Picture:
        disable: false
        parent:
        folder: Picture
        fullPath: Picture
        rule: ['*.png', '*.jpeg', '*.jpg', '*.bmp', '*.tiff', '*.gif']
        pathStatic: false
    Video:
        disable: false
        parent:
        folder: Video
        fullPath: Video
        rule: ['*.mp4', '*.mkv', '*.mka', '*.mks', '*.avi', '*.wmv', '*.flv', '*.mov']
        pathStatic: false
version_config_file: 1.0
search_folder: []
unsorted: false
doNotSort: []
lang: fr_FR
