config_sort:
    Runtime:
        path: Runtime
        ext: ['*.exe', '*.msi', '*.apk', '*.app', '*.gadget', '*.inf', '*.run', '*.vbs', '*.ws', '*.jar']
    Document:
        path: Document
        ext: ['*.xlsx', '*.docx', '*.pptx', '*.pdf']
    Archive:
        path: Archive
        ext: ['*.7z', '*.rar', '*.zip', '*.tar', '*.iso', '*.sbx', '*.gz']
    Music:
        path: Music
        ext: ['*.mp3', '*.ogg', '*.flac', '*.wav', '*.aac']
    Picture:
        path: Picture
        ext: ['*.png', '*.jpeg', '*.jpg', '*.bmp', '*.tiff', '*.gif']
    Video:
        path: Video
        ext: ['*.mp4', '*.mkv', '*.mka', '*.mks', '*.avi', '*.wmv', '*.flv', '*.mov']
unsorted: false
doNotSort: []
lang:
